# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to=b'images/')),
            ],
        ),
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('descrition', models.TextField(default=b'')),
                ('photo', models.ImageField(upload_to=b'images/')),
            ],
        ),
        migrations.CreateModel(
            name='music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to=b'images/')),
            ],
        ),
    ]
