# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='gender',
            field=models.CharField(max_length=25),
        ),
    ]
