# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20160324_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='photo',
            field=models.ImageField(upload_to=b'static/images'),
        ),
    ]
