# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20160328_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='photo',
            field=models.ImageField(upload_to=b'store/static/images'),
        ),
    ]
