# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_books_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='archive',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='books',
            name='archive',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='music',
            name='archive',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='archive',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
