# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20160402_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='photo',
            field=models.ImageField(upload_to=b'store/static/images'),
        ),
        migrations.AlterField(
            model_name='music',
            name='photo',
            field=models.ImageField(upload_to=b'store/static/images'),
        ),
    ]
