# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20160402_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='archive',
        ),
        migrations.AlterField(
            model_name='bikes',
            name='archive',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='books',
            name='archive',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='music',
            name='archive',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
