# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20160402_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='prueba',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
