# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_purchase_prueba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='prueba',
        ),
    ]
